[project]
name = "research-pr-population"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Alejandro Ouslan", email = "alejandro.ouslan@upr.edu" }]
requires-python = ">=3.13"
dependencies = ["censusforge>=0.6.1"]

[project.scripts]
research-pr-population = "prpop_repl:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["jupyter>=1.1.1", "pre-commit>=4.5.1"]
